### PR TITLE
New login procedure from Android myAudi v4.5.0

### PR DESCRIPTION
**Pull request by t0bias-r**
I check the behaviour of the current app and adopted the login procedure for Germany.
Besides the login, I only tested queries. Actions like preheating are untested.
The URL for get_vehicle_information() has changed and provides less information.

### CODE REVIEW

**Review by derhappy — APPROVED** [review]
Confirm it's working again with those changes

**Comment by titiviking** [comment]
Thanks for the great work! 
works like a charm again! (until next time Audi decides to change its API again ;-) )

**Comment by thorsten** [comment]
Works for me as well with this fix. Thank you!

**Comment by arjenvrh** [comment]
Thanks for the fix!

**Comment by adam760222** [comment]
I did all the changes in all files and still can log in - invalid credentials i got only this info. 
Maybe I did something wrong?

**Comment by t0bias-r** [comment]
> Thanks for the fix!

@arjenvrh you closed the pull request but it seems that the commits are not merged into master 🤔

**Comment by arjenvrh** [comment]
@t0bias-r Sorry about that, merged the commits now

**Pull request merged**
