### PR TITLE
Update API URLs (#1)

### LINKED ISSUE #169: Invalid credentials
Stopped working for me (I guess) 1 day ago. Deleted the integration and added again. Now I can only get 'Invalid Credentials' where I have checked they do really work when logging in to my.audi.com and they were also working before. Could it be this integration is now broken due to changes at Audi side?

### PR DESCRIPTION
**Pull request by gllmlbrt**
Tested and fixes #169 and #168

### CODE REVIEW

**Review by Naiki92 — APPROVED** [review]
Works perfectly!

**Review by bigramonk — APPROVED** [review]
works fine for me, thanks!

**Comment by thorsten** [comment]
Works with my HA installation as well. Thank you!

**Comment by rgcouto** [comment]
Works on my HA installation!

**Comment by seeder** [comment]
please merge

**Comment by rgcouto** [comment]
I'm not sure if the author of this repo is still actively mantaining it due to the message that's on README.

`Due to time limitations this project is not actively maintained anymore. It will continue to work as long as Audi does not change the API again. However, I'm open to someone else taking the lead. If you would like to become a maintainer, please contact me.`

I also don't know how to contact the owner as there are no contacts whatsoever. Maybe we should try to organize a fork of this repository.

**Comment by rklomp** [comment]
@arjenvrh , can you approve this pull request?

**Pull request merged**
