### PR TITLE
fix: clean up code with pre-commit

### PR DESCRIPTION
**Pull request by Kolbi**
No functional changes from my side except added .pre-commit-config.yaml

### CODE REVIEW

**Review by cdnninja — APPROVED** [review]
Looks good to me.   Helps clean up the code to follow ruff and other standards.

**Comment by cdnninja** [comment]
@t0bias-r @DivingUp  any concerns with merging?   This is purely cleanup.

**Comment by DivingUp** [comment]
yes, looks... please merge

**Comment by Kolbi** [comment]
Just updated to latest master and resolved conflicts.

**Comment by DivingUp** [comment]
> yes, looks... please merge

I can't check it... not chargeable car :-)...

**Pull request merged**
