### PR TITLE
feat: logger setup

### PR DESCRIPTION
**Pull request by cdnninja**
Thinking on working on adding debug statements that use domain such as:

`_LOGGER.debug(f"{DOMAIN} - vehicle response:  {vehicle}")`

As it seems getting data from users takes a little bit of work right now.    With this PR it can be enabled and disabled via GUI.

### CODE REVIEW

**Comment by cdnninja** [comment]
I also corrected sort of manifest in this to continue to resolve the hassfest errors.

**Comment by t0bias-r** [comment]
looks good to me

**Comment by DivingUp** [comment]
doesn't work....
2024-03-05 06:52:01.771 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Unable to obtain the vehicle status report of WAUZZZ4XXXXXXXX: name 'DOMAIN' is not defined
Traceback (most recent call last):
  File "/config/custom_components/audiconnect/audi_connect_account.py", line 436, in update_vehicle_statusreport
    status = await self._audi_service.get_stored_vehicle_data(self._vehicle.vin)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/audiconnect/audi_services.py", line 206, in get_stored_vehicle_data
    _LOGGER.debug(f"{**DOMAIN**} - vehicle response:  {vehicle}")

2024-03-05 07:08:21.660 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Unable to obtain the vehicle status report of WAUZZZ4MXLD001536: name 'vehicle' is not defined
Traceback (most recent call last):
  File "/config/custom_components/audiconnect/audi_connect_account.py", line 436, in update_vehicle_statusreport
    status = await self._audi_service.get_stored_vehicle_data(self._vehicle.vin)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/audiconnect/audi_services.py", line 206, in get_stored_vehicle_data
    _LOGGER.debug(f"{__name__} - vehicle response:  {**vehicle**}")


try this:
_LOGGER.debug(f"{__name__} - vehicle response:  {data}")

**Comment by cdnninja** [comment]
Sorry my top comment was an example. It isn't in the code.   I'll retest though to make sure I didn't miss a commit.

**Comment by DivingUp** [comment]
> Sorry my top comment was an example. It isn't in the code. I'll retest though to make sure I didn't miss a commit.

Now you can merge this pr… it works Like you want…debug out in ha as file for the compinent

**Comment by cdnninja** [comment]
Corrected merge conflict.  Tested in my system and works fine.  So merging.   I am thinking more debug lines like the one in this should be added to help troubleshooting.

**Pull request merged**
