### PR TITLE
Update audi_services.py

### PR DESCRIPTION
**Pull request by reisfni**
Fixes issue in Home Assistant where device/entities were not populating after adding the integration.

### CODE REVIEW

**Review by damienheiser — APPROVED** [review]
I've made the change to my HA and can confirm it works as desired.

**Comment by florie1706** [comment]
I am in Germany. Old Url works, I changed it to the Url of this pull request anyway, but that did not work for me. So I am on the old Url again which still works for me.

**Comment by agentadam-code** [comment]
WOW this works. Thanks so much.

**Comment by oleg-d** [comment]
> I am in Germany. Old Url still worked, I changed it to the Url of this pull request anyway, but that did not work for me. So I am on the old Url again which still works for me.

Same for me, old URL was working and new one is not. I'm in Finland.

**Comment by woopstar** [comment]
> > I am in Germany. Old Url still worked, I changed it to the Url of this pull request anyway, but that did not work for me. So I am on the old Url again which still works for me.
> 
> Same for me, old URL was working and new one is not. I'm in Finland.

Same for me in Denmark. Old url works, not new one.

**Comment by victorkp** [comment]
US user here -- this updated URL works.

We should be switching URLs dependent the user's specified region.

**Comment by victorkp** [comment]
I've made pull request #211, which only sets the new URL for US users. Non-US users will continue to use the old URL. @reisfni, you should close this PR.

**Pull request merged**
