### PR TITLE
Fix rejected/forbidden client error due to old X_QMAuth

### PR DESCRIPTION
**Pull request by t0bias-r**
New secrect for X_QMAuth and new user agent based on myAudi-Android/4.9.2 (Build 800237696.2205091738) Android/11

### CODE REVIEW

**Comment by synack666** [comment]
works, thanks!!

**Comment by duckend** [comment]
Many thanks - working again here also.

**Comment by bavala3010** [comment]
Thank you so much @t0bias-r  ! It's working.

**Comment by jfournierphoto** [comment]
Thanks a lot @t0bias-r you fixed it once again!!!

**Comment by TA2k** [comment]
If they change this continuously we should think about to have a file where the smart homes frameworks can fetch the current secret

**Comment by jef-pearlman** [comment]
Apologies for putting a sort-of general question here, but if I have audi_connect installed through HACS, is there a reasonably easy way to substitute this version in (until the PR is presumably merged)?  Thanks!

**Comment by shuntfield** [comment]
> Apologies for putting a sort-of general question here, but if I have audi_connect installed through HACS, is there a reasonably easy way to substitute this version in (until the PR is presumably merged)? Thanks!

You just need to edit 3-4 lines in the custom components audiconnect files pretty easy and I'm no expert

**Comment by jef-pearlman** [comment]
> > Apologies for putting a sort-of general question here, but if I have audi_connect installed through HACS, is there a reasonably easy way to substitute this version in (until the PR is presumably merged)? Thanks!
> 
> You just need to edit 3-4 lines in the custom components audiconnect files pretty easy and I'm no expert

Thanks!  To clarify, I was hoping for a way to do this through the GUI/HACS rather than manually, so if you or anyone else has a tip on that, it would be much appreciated.  

But I did a version of what you said—cloned the repository, used the github cli to checkout the PR, and copied the two relevant files over the ones in my custom_components, and it worked.  I _think_ the next HACS-based update will override that, which is good, but I should remember to confirm or explicitly ask it to reinstall.

**Comment by bbr111** [comment]
Please merge.

**Comment by allstargg** [comment]
Please merge so that the HACs version works

**Comment by shuntfield** [comment]
I'm sure it will need to be changed again, because myAudi has just updated to vr 4.10

**Comment by Nikotine1** [comment]
Working again, thanks!
It stopped working about a month ago or so (Belgium) and immediately came here to see if there was a bug report, but nobody did, so I thought I had messed something up.
If someone can explain me how to find these values, I can monitor this as well.

**Review by rklomp — APPROVED** [review]
Tested and working great! @arjenvrh , please merge

**Comment by stu1811** [comment]
Just tested in US with A4. Works great. Thanks.

**Pull request merged**
